name: base_clean_bloc
description: A new base project using bloc, Clean Architecture on Flutter 3.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  easy_localization: ^3.0.3
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  flutter_local_notifications: ^16.2.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2
  retrofit: ^4.0.3

  #Firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6

  #responsive
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0

  #UI
  adaptive_theme: ^3.4.1
  equatable: ^2.0.5
  infinite_scroll_pagination: ^4.0.0
  top_snackbar_flutter: ^3.1.0

  #database
  cryptography: ^2.7.0
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  copy_with_extension_gen: ^5.0.4
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/
    - assets/icons/
    - assets/translations/
